### ISSUE TITLE
CW-8

### ISSUE THREAD

**Issue by HarabaYaroslav** [oleksandrblazhko/ai182-garaba#22]
Запитання No 1.1 (1 бал)
Splunk Enterprise Security (Splunk ES) — це рішення преміум-класу в області безпеки, з якою група безпеки може швидко виявити за допомогою внутрішніх і зовнішніх атак і реагувати на них, а також спростити управління загрозами з одночасною мінімізацією ризиків і захистом вашого бізнесу. https://www.splunk.com/pdfs/product-briefs/[splunk-enterprise-security-ru_ru.pdf](https://www.splunk.com/pdfs/product-briefs/splunk-enterprise-security-ru_ru.pdf)

Запитання No 1.2 (1 бал)
Однорангові вузли Splunk Enterprise у версіях Splunk Enterprise до 9.0 і Splunk Cloud Platform до 8.2.2203 за замовчуванням не перевіряли сертифікати TLS під час зв’язку Splunk-to-Splunk. Однорангові зв’язки Splunk, налаштовані належним чином із дійсними сертифікатами, не були вразливими. Однак зловмисник з обліковими даними адміністратора може додати вузла без дійсного сертифіката, а з’єднання з неправильно налаштованими вузлами без дійсних сертифікатів за замовчуванням не завершуються. Для Splunk Enterprise оновіть до Splunk Enterprise версії 9.0 і налаштуйте перевірку імені хоста TLS для зв’язку Splunk-to-Splunk (https://docs.splunk.com/Documentation/Splunk/9.0.0/Security/EnableTLSCertHostnameValidation), щоб увімкнути виправлення.

Запитання No 1.3 (2 бали)
Посилання на поради, рішення та інструменти
Вибравши ці посилання, ви залишите веб-простір NIST. Ми надали ці посилання на інші веб-сайти, оскільки вони можуть містити інформацію, яка вас зацікавить. Не слід робити жодних висновків щодо інших сайтів, на які посилається ця сторінка чи ні. Можуть бути інші веб-сайти, які більш підходять для вашої мети. NIST не обов'язково підтримує висловлені погляди або погоджується з фактами, представленими на цих сайтах. Крім того, NIST не підтримує будь-які комерційні продукти, які можуть згадуватися на цих сайтах. Будь ласка, надсилайте коментарі щодо цієї сторінки на nvd@nist.gov.
Налаштувати перевірку імені хоста сертифіката TLS
Якщо ви налаштували свої екземпляри платформи Splunk на використання сертифікатів безпеки транспортного рівня (TLS) для безпечних мережевих з’єднань один з одним, ви також можете налаштувати екземпляри для перевірки імен хостів у сертифікатах, щоб переконатися, що комп’ютери, з якими екземпляри спілкуються, є тими, хто вони кажуть, що вони є. Цей доданий крок конфігурації покращує безпеку всього рівня пересилання Splunk Cloud Platform і розгортання Splunk Enterprise. Процедури в цьому розділі дійсні як для рівня пересилання Splunk Cloud Platform, так і для екземплярів Splunk Enterprise.
Щоб отримати додаткові відомості про оновлення безпеки, їх роботу та режими, які впливають на їх роботу, див. Оновлення безпеки.
Перевірка імені хоста сертифіката TLS складається з трьох окремих конфігурацій:
Конфігурація вимог до сертифіката TLS
Файл конфігурації server.conf контролює вимоги до сертифіката TLS. Ви можете налаштувати вимоги до сертифіката TLS, лише відредагувавши файл конфігурації та вказавши відповідне налаштування та значення. Це означає, що ви можете виконати цю конфігурацію лише на Splunk Enterprise або на інфраструктурі збору та пересилання для Splunk Cloud Platform, якою ви керуєте. Ви повинні ввімкнути вимогу сертифіката TLS, щоб перевірка імені хоста сертифіката працювала.
Параметр sslVerifyServerCert керує функцією вимог до сертифіката TLS. Коли ви встановлюєте для цього параметра значення «true», екземпляр платформи Splunk вимагає, щоб будь-який екземпляр платформи Splunk, до якого він підключається, надав дійсний сертифікат TLS, перш ніж це з’єднання завершиться. Якщо підключений екземпляр не надає дійсний сертифікат, перевірка вимог не виконується, і з’єднання припиняється.
Якщо перевірка вимоги виконана успішно, і ви також налаштували перевірку імені хоста сертифіката TLS, перевірка буде виконана, як описано в наступному розділі цієї теми.
Конфігурація перевірки імені хоста сертифіката TLS
Файл конфігурації server.conf також керує перевіркою імені хоста сертифіката TLS. Як і у випадку з вимогою сертифіката, ви можете налаштувати перевірку, лише відредагувавши файл конфігурації та вказавши відповідне налаштування та значення. Цю конфігурацію можна виконати лише в Splunk Enterprise або в інфраструктурі збору й пересилання для Splunk Cloud Platform, якою ви керуєте.
Майже в усіх випадках параметр sslVerifyServerName керує функцією перевірки імені хоста сертифіката TLS. Коли ви надаєте цьому параметру значення «true», екземпляр платформи Splunk, що підключається, перевіряє, що отриманий сертифікат TLS є дійсним і містить поле стандартного сертифіката шифрування X.509 «Common Name» (CN) або «Subject Alternate Name» (SAN). що відповідає імені хоста примірника, який надіслав сертифікат. Ця перевірка має відбутися до завершення підключення. Якщо підключений сервер надає сертифікат, який не відповідає цим критеріям, перевірка не вдасться, і з’єднання припиняється.
Перш ніж почати перевірку, підключений екземпляр має пройти перевірку вимог сертифіката TLS.
Конфігурація перевірки імені хоста сертифіката TLS для Splunk CLI
Інтерфейс командного рядка Splunk має дещо іншу назву налаштування для перевірки імені хоста сертифіката TLS. Коли ви запускаєте CLI для підключення до локального чи віддаленого екземпляра платформи Splunk, CLI використовує налаштування cliVerifyServerName, щоб визначити, чи потрібно перевіряти імена хостів у отриманих сертифікатах TLS.
Значення «true» для цього параметра, як і для параметра sslVerifyServerName, означає, що CLI виконує перевірку імені хоста TLS. Перевірка працює так само, як перевірка для інших екземплярів платформи Splunk.
Після ввімкнення перевірки імені хоста TLS для CLI її можна тимчасово вимкнути за допомогою аргументу CLI --no-host-name-check.

Запитання No 2.1 (1 бал)
ARIA — алгоритм симетричного блочного шифрування (розмір блоку 128 біт, ключ довжиною до 256 біт), розроблений південнокорейськими криптологами в якості шифронаціонального стандарту в Південній Кореї. У 2004 році шифр був офіційно затверджений як національний стандарт. Режим зворотний зв'язок після виходу (англ. Output Feedback, OFB) — одне із варіантів використання симетричного блочного шифру. Особливістю режиму є те, що як вхідні дані для алгоритму блочного шифрування не використовується саме повідомлення. Натомість блоковий шифр використовується для генерації псевдовипадкового потоку байтів, який за допомогою операції XOR складається з блоками відкритого тексту. Подібна схема шифрування називається потоковим шифром (англ. stream cipher).

Запитання No 2.2 (1 бал)
ARIA розроблена таким чином, щоб бути стійкою до всіх відомих атак на блок шифри [ARIA03]. Його безпеку проаналізувала група COSIC K.U.Leuven у Бельгії [ARIAEVAL], і не виявлено недоліків безпеки.

Запитання No 2.3 (1 бал)
Недоліки
- Для вибору вектора ініціалізації потрібен добрий генератор випадкових чисел.
- Кожен сеанс подовжується однією блок.
Переваги
- полягає у повному збігу операцій шифрування та розшифрування
- у цьому режимі не потрібно проводити операцію доповнення відкритого тесту.
- в порівнянні з режимом CFB: помилки, що виникають в результаті передачі каналом з шумом, при дешифруванні не «розмазуються» по всьому шифротексту, а локалізуються в межах одного блоку.

**Comment by oleksandrblazhko** [comment]
5 бали
