### ISSUE TITLE
CW-9

### ISSUE THREAD

**Issue by HarabaYaroslav** [oleksandrblazhko/ai182-garaba#23]
Запитання No 1.1 (1 бал)
TYPO3 (тайпо три) — система керування сайтами (CMS/CMF) з відкритим вихідним кодом та вільною ліцензією. Є гнучкою системою, що розширюється, з великою кількістю модулів і функцій. Написана на PHP, для зберігання даних використовує будь-яку реляційну базу даних, яку підтримує TYPO3 DBAL, включаючи MySQL, Oracle Database, PostgreSQL та інші. Працює на таких серверах, як Apache або IIS, та на більшості операційних систем, таких як Linux, Microsoft Windows, FreeBSD, Mac OS X та OS/2. Система створена Каспером Скорхеєм та розповсюджується безкоштовно під ліцензією GNU GPL. https://ua.wikipedia.org/wiki/TYPO3

Запитання No 1.2 (1 бал)
TYPO3 — це система керування веб-контентом із відкритим кодом на PHP. У версіях до 8.7.49, 9.5.38, 10.4.33, 11.5.20 і 12.1.1 TYPO3 вразливий до неправильної автентифікації. Обмеження входу в зовнішній інтерфейс для певних користувачів, організованих у різних папках зберігання (розділах), можна обійти. Потенційний зловмисник може використати цю неоднозначність в іменах користувачів, щоб отримати доступ до іншого облікового запису, проте облікові дані повинні бути відомі зловмиснику. Цю проблему виправлено у версіях 8.7.49 ELTS, 9.5.38 ELTS, 10.4.33, 11.5.20, 12.1.1.

Запитання No 1.3 (1 бал)
References to Advisories, Solutions, and Tools
Ви можете вибрати ці links, ви будете робити NIST webspace. Будь ласка, надішліть ці links до інших веб-сайтів тому, що вони можуть мати інформацію, що ви повинні бути зацікавлені в вас. No inferences повинні бути витягнуті на облік інших місць, коли referenced, або не, з цієї сторінки. Там можуть бути інші веб-сайти, які є більш придатними для вашої purpose. NIST does необов'язково endorse the views expressed, або concur with the facts presentd on these sites. Further, NIST does not endorse any commercial products що можуть бути mentioned on thes sites. Please address comments про цю сторінку до nvd@nist.gov.

CVSS: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:L/A:N/E:F/RL:O/RC:C ( 5.5)
проблема
Обмеження входу в зовнішній інтерфейс для певних користувачів, організованих у різних папках зберігання (розділах), можна обійти. Потенційний зловмисник може використати цю неоднозначність в іменах користувачів, щоб отримати доступ до іншого облікового запису, проте облікові дані повинні бути відомі зловмиснику.

Рішення
Оновлення до TYPO3 версій 8.7.49 ELTS, 9.5.38 ELTS, 10.4.33, 11.5.20, 12.1.1, які вирішують описану вище проблему.

Кредити
Дякуємо члену команди безпеки TYPO3 Торбену Хансену, який повідомив про цю проблему, і члену основної групи та команди безпеки TYPO3 Оліверу Хадеру, який вирішив проблему.

Запитання No 2.1 (1 бал)
Крадіжка 
Фізичний автентифікатор викрадений зловмисником. 
Викрадено апаратний криптографічний пристрій.
Пристрій OTP викрадено.
Викрадено пошуковий секретний автентифікатор.
Крадуть мобільний телефон.

Запитання No 2.2 (1 бал)
Типове використання

Користувачі використовують автентифікатор — друкований або електронний — для пошуку відповідних секретів, необхідних для відповіді на підказку верифікатора. Наприклад, користувача можуть попросити надати певну підмножину числових або символьних рядків, надрукованих на картці у форматі таблиці.

Розглядання зручності використання для типового використання включають:

Досвід користувача під час введення секретів пошуку.
Враховуйте складність і розмір підказок. Чим більшу підмножину секретів пропонує користувач шукати, тим більші наслідки для зручності використання. При виборі кількості та складності секретів пошуку для автентифікації слід враховувати як когнітивне навантаження, так і фізичні труднощі для входу.

**Comment by oleksandrblazhko** [comment]
4 бали
